# Generated by Django 2.2.4 on 2020-10-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
