# Generated by Django 2.2.4 on 2020-10-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='test',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
