# Generated by Django 2.2.4 on 2020-10-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201017_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
        migrations.AddField(
            model_name='profile',
            name='student',
            field=models.NullBooleanField(),
        ),
    ]
