# Generated by Django 2.2.4 on 2020-10-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201017_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='professional',
            field=models.NullBooleanField(),
        ),
    ]
