# Generated by Django 2.2.4 on 2020-10-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='professional',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student',
            field=models.BooleanField(null=True),
        ),
    ]
