# Generated by Django 2.2.4 on 2020-10-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student',
            field=models.BooleanField(null=True),
        ),
    ]
