# Generated by Django 2.2.4 on 2020-10-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='test',
            new_name='looking_for',
        ),
        migrations.AddField(
            model_name='profile',
            name='affiliation',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_to_offer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
