# Generated by Django 2.2.4 on 2020-10-30 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201029_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_request',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.AddField(
            model_name='friend_request',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='friend_request',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='friend_request',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
