# Generated by Django 3.1.3 on 2020-11-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20201107_2215'),
        ('users', '0031_auto_20201108_0313'),
    ]

    operations = [
    ]
