# Generated by Django 3.1.3 on 2020-11-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20201111_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='status',
        ),
    ]
